export const GET_CERTIFICATES = "GET_CERTIFICATES";
export const GET_CERTIFICATES_FAIL = "GET_CERTIFICATES_FAIL";
export const GET_CERTIFICATES_SUCCESS = "GET_CERTIFICATES_SUCCESS";
export const POST_CERTIFICATES = "POST_CERTIFICATES";
export const UPDATE_CERTIFICATES = "UPDATE_CERTIFICATES";
export const DELETE_CERTIFICATES = "DELETE_CERTIFICATES";
export const GET_CERTIFICATES_BY_ID = "GET_CERTIFICATES_BY_ID";
export const SET_SHOULD_UPDATE_CERTIFICATE = "SET_SHOULD_UPDATE_CERTIFICATE";
