export const GET_ALL_FAMILY_MEMBERS = "GET_ALL_FAMILY_MEMBERS";
export const GET_ALL_FAMILY_MEMBERS_FAIL = "GET_ALL_FAMILY_MEMBERS_FAIL";
export const GET_ALL_FAMILY_MEMBERS_SUCCESS = "GET_ALL_FAMILY_MEMBERS_SUCCESS";
export const POST_FAMILY_MEMBER = "POST_FAMILY_MEMBER";
export const UPDATE_FAMILY_MEMBER = "UPDATE_FAMILY_MEMBER";
export const DELETE_FAMILY_MEMBER = "DELETE_FAMILY_MEMBER";
export const GET_FAMILY_MEMBER_BY_ID = "GET_FAMILY_MEMBER_BY_ID";
export const SET_SHOULD_UPDATE_FAMILY = "SET_SHOULD_UPDATE_FAMILY";