export const GET_ALL_STAFF = "GET_ALL_STAFF";
export const GET_STAFF_BY_ID = "GET_STAFF_BY_ID";
export const GET_STAFF_BY_ID_SUCCESS = "GET_STAFF_BY_ID_SUCCESS";
export const GET_STAFF_BY_ID_FAIL = "GET_STAFF_BY_ID_FAIL";
export const POST_STAFF_TO_LIST = "POST_STAFF_TO_LIST";
export const POST_STAFF_TO_LIST_SUCCESS = "POST_STAFF_TO_LIST_SUCCESS";
export const PUT_STAFF_TO_LIST = "PUT_STAFF_TO_LIST";
export const PUT_STAFF_TO_LIST_SUCCESS = "PUT_STAFF_TO_LIST_SUCCESS";
export const DELETE_STAFF = "DELETE_STAFF";
export const SEARCH_BY_PAGE = "SEARCH_BY_PAGE";
export const SEARCH_BY_PAGE_SUCCESS = "SEARCH_BY_PAGE_SUCCESS";
export const SEARCH_BY_PAGE_FAIL = "SEARCH_BY_PAGE_FAIL";
export const SET_SHOULD_UPDATE = "SET_SHOULD_UPDATE";
export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
export const GET_IMAGE = "GET_IMAGE";
export const SET_IMAGE = "SET_IMAGE";
export const SET_ITEM ="SET_ITEM";



